import Head from "next/head";
import styles from "../styles/Home.module.css";
import { client } from "../utils/shopify-client";
import Link from "next/link";
import { Image, Card } from "semantic-ui-react";


export default function Home({ products, policies, infos }) {
  console.log(products);
  // const [sessiocCheckout, setSessionCheckout] = useState();
  // useEffect(() => {
  //   (async () => {
  //     const session = await client.checkout.create();
  //     console.log("session is", session);
  //     setSessionCheckout(session);
  //   })();
  // }, []);

  // useEffect(() => {
  //  async function session(){
  //   const session = await client.checkout.create();
  //   console.log("session is", session);
  //  }

  //  session();
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Nextttt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* itemsPerRow={4} */}
      <div>
        <Card.Group xs={16} sm={8} lg={4}>
          {products.map((product) => (
            <Link href={`/product/${product.id}`} key={product.id}>
              <Card>
                {/* <Link href={`/product/${product.id}`} key={product.id}> */}
                <Image src={product.images[0].src} />
                {/* </Link> */}
                <Card.Content>
                  <a>
                    <h3>{product.title}</h3>
                  </a>
                  <br />
                  <span>
                    <h4>RS :<s >{product.variants[0].compareAtPrice}</s></h4>
                    <h3>RS :{product.variants[0].price} </h3>
                  </span>
                </Card.Content>
              </Card>
            </Link>
          ))}
        </Card.Group>
      </div>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const products = await client.product.fetchAll(); // Fetch product
  const infos = await client.shop.fetchInfo(); // Fetch shop Info if you think about SEO and title and ... to your page
  const policies = await client.shop.fetchPolicies(); // fetch shop policy if you have any
  return {
    props: {
      infos: JSON.parse(JSON.stringify(infos)),
      policies: JSON.parse(JSON.stringify(policies)),
      products: JSON.parse(JSON.stringify(products)),
    },
  };
};
